// deno-lint-ignore-file no-import-prefix no-unversioned-import
/**
 * error-notifier — Supabase Edge Function scaffold
 *
 * Generated by @supabase-alerts/cli
 * Docs: https://github.com/your-org/supabase-alerts#readme
 *
 * This function can be called from:
 *   - SQL watchdogs (via pg_net.http_post)
 *   - Other edge functions directly
 *   - Any HTTP client
 *
 * Expected request body:
 *   {
 *     "context":  "db/long-queries",         // where the error came from
 *     "severity": "warn" | "error" | ...,    // optional, defaults to "error"
 *     "meta":     { ... }                    // optional key-value metadata
 *   }
 *
 * Or pass a raw Error as JSON:
 *   { "context": "...", "error": "message string or Error.message" }
 */

import { createNotifier } from "jsr:@supabase-alerts/core";

const alert = createNotifier({
  channel: "__CHANNEL__",

  // Telegram (remove if using slack/discord)
  telegramToken: Deno.env.get("TELEGRAM_BOT_TOKEN"),
  telegramChatId: Deno.env.get("TELEGRAM_CHAT_ID"),

  // Slack (remove if using telegram/discord)
  slackWebhookUrl: Deno.env.get("SLACK_WEBHOOK_URL"),

  // Discord (remove if using telegram/slack)
  discordWebhookUrl: Deno.env.get("DISCORD_WEBHOOK_URL"),

  projectName: __PROJECT_NAME__,
  minSeverity: "__MIN_SEVERITY__",

  retry: {
    maxAttempts: 3,
    baseDelayMs: 1000,
    jitterMs: 500,
  },
});

Deno.serve(async (req: Request) => {
  // Health check
  if (req.method === "GET") {
    return new Response(
      JSON.stringify({ status: "ok", service: "error-notifier" }),
      { headers: { "Content-Type": "application/json" } },
    );
  }

  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  let body: Record<string, unknown>;

  try {
    body = await req.json();
  } catch {
    return new Response("Invalid JSON body", { status: 400 });
  }

  const context = String(body.context ?? "unknown");
  const severity = (body.severity as string) || "error";
  const meta = (body.meta as Record<string, unknown>) ?? {};
  const errorMsg = String(body.error ?? body.message ?? "Alert triggered");

  // Fire-and-forget — this function returns before delivery completes
  alert.notify(context, new Error(errorMsg), severity as never, meta);

  return new Response(
    JSON.stringify({ accepted: true }),
    {
      status: 202,
      headers: { "Content-Type": "application/json" },
    },
  );
});
